name: Publish
on:
  workflow_dispatch:
  push:

jobs:
  build:
    if: "contains(github.event.head_commit.message, '[publish]') || github.event_name == 'workflow_dispatch'"
    runs-on: ubuntu-24.04
    steps:
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - name: Upload to Maven
        run: |
          chmod +x gradlew
          ./gradlew publish --stacktrace
        env:
          KTT_MAVEN_USERNAME: ${{ secrets.KTT_MAVEN_USERNAME }}
          KTT_MAVEN_TOKEN: ${{ secrets.KTT_MAVEN_TOKEN }}